name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

    - name: make
      run: make

    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: compiled-binaries
        path: ./build
